version: '3'
services:
  backend:
    image: docker.pkg.github.com/${REPO_OWNER:-temp}/sigfox-platform/backend:${TAG:-latest}
    container_name: backend
    build:
      context: backend
      args:
        - GIT_REV=${TAG}
    restart: 'always'
    env_file: env/backend.env
    command: yarn start
    ports:
      - '3000:3000'

  primus:
    image: docker.pkg.github.com/${REPO_OWNER:-temp}/sigfox-platform/primus:${TAG:-latest}
    container_name: primus
    build: primus
    restart: 'always'
    env_file: env/primus.env
    command: yarn start
    ports:
      - '2333:2333'

  frontend:
    image: docker.pkg.github.com/${REPO_OWNER:-temp}/sigfox-platform/frontend:${TAG:-latest}
    container_name: frontend
    build:
      context: frontend
      args:
        - BUILD_ENV=${BUILD_ENV:-prod}
        - SERVER_NAME=${SERVER_NAME}
        - API_URL=${API_URL:-http://localhost:3000}
        - API_VERSION=${API_VERSION:-api}
        - PRIMUS_URL=${PRIMUS_URL:-http://localhost:2333}
        - CALLBACK_URL=${CALLBACK_URL:-http://api.localhost}
    restart: 'always'
    ports:
      - '4200:80'
