name: docker build

on:
  push:
    branches: [master]

jobs:
  build-staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
      TAG: ${{ secrets.TAG }}
      SERVER_NAME: ${{ secrets.SERVER_NAME }}
      API_URL: ${{ secrets.API_URL }}
      PRIMUS_URL: ${{ secrets.PRIMUS_URL }}
      CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
      REPO_OWNER: innovation-farm
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Build applications
        run: docker-compose build

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com/${REPO_OWNER}/sigfox-platform
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push application packages
        run: docker-compose push

  build-production:
    runs-on: ubuntu-latest
    environment: production
    env:
      TAG: ${{ secrets.TAG }}
      SERVER_NAME: ${{ secrets.SERVER_NAME }}
      API_URL: ${{ secrets.API_URL }}
      PRIMUS_URL: ${{ secrets.PRIMUS_URL }}
      CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
      REPO_OWNER: innovation-farm
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Build applications
        run: docker-compose build

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com/${REPO_OWNER}/sigfox-platform
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push application packages
        run: docker-compose push
