name: docker build

on:
  push:
    branches: [master]

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: innovation-farm
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Build applications
        run: docker-compose build

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com/${{ github.repository_owner }}/sigfox-platform
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push application packages
        run: docker-compose push
